matrix:
  include:
  - language: android
    env: TO_TEST=ANDROID
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8
    env: TO_TEST=IOS
  fast_finish: true
android:
  components:
  - platform-tools
  - tools
  - android-23
  - build-tools-23.0.3
  - extra-android-m2repository
  - extra-google-m2repository
  - sys-img-armeabi-v7a-android-19
install:
- rvm install 2.2.0
- sudo pip install boto3
- if [ "$TO_TEST" = "ANDROID" ]; then gem install calabash-android; fi
- if [ "$TO_TEST" = "IOS" ]; then gem install calabash-cucumber; fi
before_script:
- if [ "$TO_TEST" = "ANDROID" ]; then chmod 755 createEmulator.sh; fi
- if [ "$TO_TEST" = "ANDROID" ]; then ./createEmulator.sh; fi
script:
- if [ "$TO_TEST" = "ANDROID" ]; then chmod 755 androidTest.sh; fi
- if [ "$TO_TEST" = "ANDROID" ]; then ./androidTest.sh; fi
- if [ "$TO_TEST" = "IOS" ]; then chmod 755 iosTest.sh; fi
- if [ "$TO_TEST" = "IOS" ]; then ./iosTest.sh; fi
notifications:
  email:
  - mobilecoreteam@bazaarvoice.com
env:
  global:
  - secure: KjHSstDYdU9glE6ibAeRS7ez4a6b2n3GmKeuwIrbXna27uJMKxa9bCXAtsKvlBKPxnvaPlTJ5BBR8lvD/DKeil9ZIt7mHUNw+ZF9Gq4WzGpAtZW2FAlU6uL1FxOuJqlcCia9Lb9umf/52lVqhxA3MsunjzoW5YSV0sECU1ZtXYaiPvjXus/BwSE7SgLunF4eHT2b8ya2yEMnwM2c/GUUl1q3XJyz91YgYgTITcrseqFuJXvU251wHZ71MZQRjnbDp/z5tOTJ0hbESi+6lBmQHxSCyo57iMBj+DpiR1wauTGrmhVgRauKFwvyME0aEXDYzv3DRKEYV5JtiNr7iUaxiMJN952c5pnaMS2pyEca3HDAWPG5cgqExblfQEem4h308Qf3f1JRhKyeaxkGYYkxVeKcAJ5xjOZyKbkUutpY1frbRFJK4yi647vwZOkPcJ94OkCWY0sgFqZOqA+rNJ4gM9WZoQjCxDm/5vHRdExeaxk9LQW9VzT49RKWDOZv4RRUvf87RAFsrnkWTJaG6F5eWhwFU3UHLm3dULArB8GxyV9O+l2YrqopYbkAyoEpoJtIKpGk7MFL/YOFTiUfkqDt+bDLdi8B4AWDXYqbLyrmeQW6mqF6o3qJ6fL2Sq/euNAzZ3a02PbWXUi8y05VZaskKNJGo1DPqerq+Da1RIVIboo=
  - secure: E94Qbz2FFj0aN3P8Vrzx/GSpYSdETxF7y3YQeigBbGiK8VJj/WHUZ1S3jQgp2RAvBLGB70rW4W3bahd1qltQtRYcajdhyavAAPsOt/UyOQnvQfoG+xJvOC659bahMOLv+Rio0i4Ccv5IJevN++FkpR+xZcJN782CIXJJ/Fsv9O/QOOm8t0qaWON8fsryjwIAyRVz8TlqLcDSbSBjZMd3cZh6EfEx2MxcGEIskLScfsCZUZCVOb0QwNAd+IxCX7X13v/jar8xYegZVmlwd7c0n3qkQkzEa1Ovfmzz3WFEv+J516vsMSI3LJivesYBbxHQwucTKeFCfoexQzVAmBwXt8LwX7MjdaaTYbDsCHOJu8163EXVtw480ztGITuUUVEPR1CtsO+5R7D0ePpgtU0lNGlYvVxXw/9h4nOI2THqJeokRtLeE4uvKPesu9WPldOU4pzfRTmArocKcIThf7hvELS9kPhyyxcYFLzPYLtYqg6F3aAXkv6drgwvHe2eAzi662LJNKz26kr0jJAEn5I0aVTi56i2CJUkZcqe4cm+KCPXRiEovPF1hXjfwNtiZ5ZKaq/IcoYn5r9/N7JBg/Y/X78Wvdh017AEPN0klBdWH9Vf5KL4NUY93OOo3SQ+PjJ9iSVaVSaQ4pYJhBI1u3NvRlmi1Q/aZhn0r/VE80ZTMC0=
